kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: doomain-ir
  #namespace: production

spec:
  rules:
    - host: jenkins.doomain.ir
      http:
        paths:
          - path: /
            backend:
              serviceName: jenkins-svc
              servicePort: 8080

