apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
    - name: server
      image: server
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      readinessProbe:
        httpGet:
          path: /
          port: 5000



