kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    type: local
    name: apparsfiles  
spec:
  capacity:
    storage: 5Gi 
  volumeMode: Filesystem  
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storageclass
  nfs: 
    path: /nfs/public/mysql/
    server: nfs.akks.ir
    readOnly: false

