apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
