apiVersion: v1                                                                                                                                                                                                                              
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  namespace: webs
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

