apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: webs
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: PHP_INI_SCAN_DIR
          value: :/usr/local/etc/php/conf.custom
        - name: WORDPRESS_DB_HOST
          value: mysql-service.dbs.svc.cluster.local
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wp-pv
          mountPath: /var/www/html
        - name: php-config
          mountPath: /usr/local/etc/php/conf.custom          
      volumes:
      - name: wp-pv
        persistentVolumeClaim:
          claimName: wp-pvc
      - name: php-config
        configMap:
          name: wp-config
