apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: webs
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30012
      name: wp
  selector:
    app: wordpress

