apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx 
   labels:
     app: nginx
spec:
  template:
    metadata:
       name: nginx
       labels:
         app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-www
        persistentVolumeClaim:
          claimName: nginx-pvc
  replicas: 3
  selector:
    matchLabels:
      app: nginx

