apiVersion: v1
kind: Pod
metadata:
  name: nginxapp
  labels:
    name: nginxlabel
spec:
  containers:
    - name: nginxc
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2
                

