apiVersion: v1
kind: Pod
metadata:
  name: nginxapp
spec:
  containers:
    - name: nginxc
      image: nginx
  nodeSelector:
    size: Large          
# size must be defined for node like this:
# kubectl label nodes mynode size=Large

