apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  ports:
    - targetPort: 3306
      port: 3306
      nodePort: 30001
      name: mysql
  selector:
    app: mysql
    #type: back-end
