apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002
      name: wp
  selector:
    app: wordpress
    #type: back-end
